services:
  capitalmarkets-chatbot-backend:
    build:
      context: .
      no_cache: true
      dockerfile: Dockerfile.backend
    image: capitalmarkets-chatbot-image-backend:latest
    volumes:
      - ~/.aws/credentials:/root/.aws/credentials:ro
      - ~/.aws/config:/root/.aws/config:ro
      - ~/.aws/sso/cache:/root/.aws/sso/cache:rw  # Only make cache writable
    ports:
      - "8000:8000"
    restart: always
    container_name: capitalmarkets-chatbot-container