env:
  NODE_ENV: prod
  
envSecrets:
  MONGODB_URI: capitalmarkets-react-agent-crypto
  DATABASE_NAME: capitalmarkets-react-agent-crypto
  APP_NAME: capitalmarkets-react-agent-crypto
  VOYAGE_API_KEY: capitalmarkets-react-agent-crypto
  TAVILY_API_KEY: capitalmarkets-react-agent-crypto
  AWS_REGION: capitalmarkets-react-agent-crypto
  CHAT_COMPLETIONS_MODEL_ID: capitalmarkets-react-agent-crypto
  EMBEDDINGS_MODEL_ID: capitalmarkets-react-agent-crypto
  AGENT_PROFILES_COLLECTION: capitalmarkets-react-agent-crypto
  CHECKPOINTS_AIO_COLLECTION: capitalmarkets-react-agent-crypto
  CHECKPOINTS_WRITES_AIO_COLLECTION: capitalmarkets-react-agent-crypto
  REPORTS_COLLECTION_CRYPTO_ANALYSIS: capitalmarkets-react-agent-crypto
  REPORT_CRYPTO_ANALYSIS_VECTOR_INDEX_NAME: capitalmarkets-react-agent-crypto
  REPORTS_COLLECTION_CRYPTO_NEWS: capitalmarkets-react-agent-crypto
  REPORT_CRYPTO_NEWS_VECTOR_INDEX_NAME: capitalmarkets-react-agent-crypto
  REPORTS_COLLECTION_CRYPTO_SM: capitalmarkets-react-agent-crypto
  REPORT_CRYPTO_SM_VECTOR_INDEX_NAME: capitalmarkets-react-agent-crypto
  REPORT_VECTOR_FIELD: capitalmarkets-react-agent-crypto
  NODE_ENV: capitalmarkets-react-agent-crypto

serviceAccount:
  enabled: true
  irsa:
    accountId: "275662791714"
    roleName: "kanopy-prod-cicd-irsa"